/*                              50 KEY MATRIX / LAYOUT MAPPING (Hillside Dactyl 50)
 *
 *  ╭─────────────────────────────────╮ ╭─────────────────────────────────╮
 *  │  0   1   2   3   4   5          │ │           6   7   8   9  10  11 │
 *  │ 12  13  14  15  16  17          │ │          18  19  20  21  22  23 │
 *  │ 24  25  26  27  28  29          │ │          30  31  32  33  34  35 │
 *  ╰────────╮ 36  37 ╭───────╮ 38 39 │ │ 40 41 ╭───────╮ 42 43 ╭─────────╯
 *           │        │ 44 45 │ 46    │ │    47 │ 48 49 │
 *           ╰────────╯       ╰───────╯ ╰───────╯       ╰────────╯
 *
 *  Logical labels (X_* slots are extras — bind via the matching macros in
 *  hillside_d50.keymap):
 *
 *      pos 0/11/12/23/24/35       outer pinky column → X_LT/X_LM/X_LB and
 *                                                      X_RT/X_RM/X_RB
 *      pos 36/37 (left)           raised pair        → X_LR (2 keys)
 *      pos 42/43 (right)          raised pair        → X_RR (2 keys)
 *      pos 38/39 (left)           thumb upper row    → X_LU (2 keys)
 *      pos 40/41 (right)          thumb upper row    → X_RU (2 keys)
 *      pos 44 (LH2) / 49 (RH2)    outer-bottom thumb → X_LH / X_RH
 *
 *  Shared physical vocabulary (agents and humans) is defined at the bottom of
 *  this file: L_COL1_TOP .. R_COL6_BOT plus cluster aliases. Columns count 1-6
 *  from the outer pinky to the inner index, mirrored on both hands.
 *
 *  ╭─────────────────────────────────╮ ╭─────────────────────────────────╮
 *  │ X_LT LT4 LT3 LT2 LT1 LT0        │ │       RT0 RT1 RT2 RT3 RT4 X_RT  │
 *  │ X_LM LM4 LM3 LM2 LM1 LM0        │ │       RM0 RM1 RM2 RM3 RM4 X_RM  │
 *  │ X_LB LB4 LB3 LB2 LB1 LB0        │ │       RB0 RB1 RB2 RB3 RB4 X_RB  │
 *  ╰────────╯ X_LR ╭──────╮ X_LU     ╯ ╰   X_RU ╭──────╮ X_RR ╰──────────╯
 *                  │ X_LH LH1 LH0   │ │ RH0 RH1 X_RH │
 *                  ╰────────────────╯ ╰──────────────╯
 */

#pragma once

#define LT0  5  // left-top alpha row
#define LT1  4
#define LT2  3
#define LT3  2
#define LT4  1

#define RT0  6  // right-top alpha row
#define RT1  7
#define RT2  8
#define RT3  9
#define RT4 10

#define LM0 17  // left-middle alpha row
#define LM1 16
#define LM2 15
#define LM3 14
#define LM4 13

#define RM0 18  // right-middle alpha row
#define RM1 19
#define RM2 20
#define RM3 21
#define RM4 22

#define LB0 29  // left-bottom alpha row
#define LB1 28
#define LB2 27
#define LB3 26
#define LB4 25

#define RB0 30  // right-bottom alpha row
#define RB1 31
#define RB2 32
#define RB3 33
#define RB4 34

#define LH0 46  // inner-left thumb
#define LH1 45  // middle-left thumb
#define LH2 44  // outer-left thumb (X_LH slot)

#define RH0 47  // inner-right thumb
#define RH1 48  // middle-right thumb
#define RH2 49  // outer-right thumb (X_RH slot)

/* ---------------------------------------------------------------------------
 * Shared physical vocabulary (agents and humans)
 *
 * Columns count outer-to-inner on each half and are mirrored, so col 1 is the
 * outer pinky on both hands:
 *
 *   col 1 outer pinky | col 2 pinky | col 3 ring
 *   col 4 middle      | col 5 index | col 6 inner index
 *
 * Rows are TOP / HOME (the row with homerow mods) / BOT. Thumb and cluster
 * keys are named by cluster plus inner/outer position instead of column.
 *
 * Use these aliases when talking about a key ("move Esc to L_COL3_TOP") and in
 * new code; the legacy label families (LT, LM, LB, RT, RM, RB, LH, RH and the
 * X_ extras) and the 0-49 positions stay the machine-facing canonical names
 * for combos, draw, and CI. See draw/hillside_d50-positions.md (generated by
 * `just draw-d50`) for the full position card.
 * ------------------------------------------------------------------------ */

/* Left main block: 6 columns x 3 rows (col 1 = outer pinky) */
#define L_COL1_TOP   0   /* X_LT */
#define L_COL1_HOME 12   /* X_LM */
#define L_COL1_BOT  24   /* X_LB */
#define L_COL2_TOP  LT4
#define L_COL2_HOME LM4
#define L_COL2_BOT  LB4
#define L_COL3_TOP  LT3
#define L_COL3_HOME LM3
#define L_COL3_BOT  LB3
#define L_COL4_TOP  LT2
#define L_COL4_HOME LM2
#define L_COL4_BOT  LB2
#define L_COL5_TOP  LT1
#define L_COL5_HOME LM1
#define L_COL5_BOT  LB1
#define L_COL6_TOP  LT0
#define L_COL6_HOME LM0
#define L_COL6_BOT  LB0

/* Right main block: 6 columns x 3 rows (col 1 = outer pinky) */
#define R_COL1_TOP  11   /* X_RT */
#define R_COL1_HOME 23   /* X_RM */
#define R_COL1_BOT  35   /* X_RB */
#define R_COL2_TOP  RT4
#define R_COL2_HOME RM4
#define R_COL2_BOT  RB4
#define R_COL3_TOP  RT3
#define R_COL3_HOME RM3
#define R_COL3_BOT  RB3
#define R_COL4_TOP  RT2
#define R_COL4_HOME RM2
#define R_COL4_BOT  RB2
#define R_COL5_TOP  RT1
#define R_COL5_HOME RM1
#define R_COL5_BOT  RB1
#define R_COL6_TOP  RT0
#define R_COL6_HOME RM0
#define R_COL6_BOT  RB0

/* Left clusters (inner/outer as seen from the hand) */
#define L_RAISE_OUTER       36   /* X_LR (1) */
#define L_RAISE_INNER       37   /* X_LR (2) */
#define L_THUMB_UPPER_OUTER 38   /* X_LU (1) */
#define L_THUMB_UPPER_INNER 39   /* X_LU (2) */
#define L_THUMB_LOWER_OUTER LH2
#define L_THUMB_LOWER_MID   LH1
#define L_THUMB_LOWER_INNER LH0

/* Right clusters (inner/outer as seen from the hand) */
#define R_THUMB_UPPER_INNER 40   /* X_RU (1) */
#define R_THUMB_UPPER_OUTER 41   /* X_RU (2) */
#define R_RAISE_INNER       42   /* X_RR (1) */
#define R_RAISE_OUTER       43   /* X_RR (2) */
#define R_THUMB_LOWER_INNER RH0
#define R_THUMB_LOWER_MID   RH1
#define R_THUMB_LOWER_OUTER RH2
