#!/usr/bin/env python3
"""Generate the Hillside D50 physical position card.

Reads the shared vocabulary (config/key-labels/hillside_d50.h), the matrix
transform (position -> RC), the physical layout (draw geometry), and the parsed
Base layer, then writes:

    draw/hillside_d50-positions.md    exhaustive position table
    draw/hillside_d50-positions.svg   numbered physical map

Regenerated by `just draw-d50`; CI fails if the tracked artifacts drift.
"""

from __future__ import annotations

import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "config/key-labels/hillside_d50.h"
TRANSFORM = ROOT / "config/boards/shields/hillside_d50/hillside_d50_common.dtsi"
LAYOUT = ROOT / "config/boards/shields/hillside_d50/hillside_d50-layouts.dtsi"
PARSED = ROOT / "draw/hillside_d50.yaml"
MD_OUT = ROOT / "draw/hillside_d50-positions.md"
SVG_OUT = ROOT / "draw/hillside_d50-positions.svg"

COLUMN_NAMES = {
    1: "outer pinky",
    2: "pinky",
    3: "ring",
    4: "middle",
    5: "index",
    6: "inner index",
}
ROW_NAMES = {"TOP": "top", "HOME": "home", "BOT": "bottom"}

ALIAS_RE = re.compile(
    r"([LR])_(COL[1-6]_(TOP|HOME|BOT)"
    r"|RAISE_(OUTER|INNER)"
    r"|THUMB_UPPER_(OUTER|INNER)"
    r"|THUMB_LOWER_(OUTER|INNER|MID))"
)
LABEL_RE = re.compile(r"((LT|LM|LB|RT|RM|RB)[0-4]|(LH|RH)[0-2])")

# Positions without a numeric LT/LH-style label, named by their D50 slot.
LEGACY_SLOTS = {
    0: "X_LT",
    11: "X_RT",
    12: "X_LM",
    23: "X_RM",
    24: "X_LB",
    35: "X_RB",
    36: "X_LR (1)",
    37: "X_LR (2)",
    38: "X_LU (1)",
    39: "X_LU (2)",
    40: "X_RU (1)",
    41: "X_RU (2)",
    42: "X_RR (1)",
    43: "X_RR (2)",
}

GROUPS = {
    "main": ("#fafafa", "#c9c9c9"),
    "raise": ("#ffe3bf", "#e0a868"),
    "upper": ("#d3e9fb", "#87b5d8"),
    "lower": ("#d9efd9", "#8fb98f"),
}

SVG_FONT = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"


def parse_defines(path: Path) -> dict[str, str]:
    defines: dict[str, str] = {}
    for line in path.read_text().splitlines():
        match = re.match(r"\s*#define\s+(\w+)\s+(\w+)\b", line)
        if match:
            defines[match.group(1)] = match.group(2)
    return defines


def resolve(name: str, defines: dict[str, str]) -> str:
    seen: set[str] = set()
    while name in defines and name not in seen:
        seen.add(name)
        name = defines[name]
    return name


def parse_positions(defines: dict[str, str], pattern: re.Pattern[str]) -> dict[int, str]:
    by_pos: dict[int, str] = {}
    for name in defines:
        if pattern.fullmatch(name):
            by_pos[int(resolve(name, defines))] = name
    return by_pos


def parse_transform() -> list[tuple[int, int]]:
    text = TRANSFORM.read_text()
    map_match = re.search(r"map\s*=\s*<(.*?)>;", text, re.S)
    assert map_match, f"no transform map found in {TRANSFORM}"
    cells = re.findall(r"RC\((\d+),\s*(\d+)\)", map_match.group(1))
    assert len(cells) == 50, f"expected 50 transform cells, found {len(cells)}"
    return [(int(row), int(col)) for row, col in cells]


def parse_layout() -> list[tuple[int, int, int, int]]:
    attrs = re.findall(
        r"&key_physical_attrs\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)",
        LAYOUT.read_text(),
    )
    assert len(attrs) == 50, f"expected 50 physical keys, found {len(attrs)}"
    return [(int(w), int(h), int(x), int(y)) for w, h, x, y, *_ in attrs]


def physical(alias: str) -> str:
    side, rest = alias.split("_", 1)
    hand = "left" if side == "L" else "right"
    col = re.fullmatch(r"COL(\d)_(TOP|HOME|BOT)", rest)
    if col:
        number = int(col.group(1))
        return f"{hand} column {number} ({COLUMN_NAMES[number]}), {ROW_NAMES[col.group(2)]} row"
    raise_ = re.fullmatch(r"RAISE_(OUTER|INNER)", rest)
    if raise_:
        return f"{hand} raise, {raise_.group(1).lower()}"
    upper = re.fullmatch(r"THUMB_UPPER_(OUTER|INNER)", rest)
    if upper:
        return f"{hand} thumb upper, {upper.group(1).lower()}"
    lower = re.fullmatch(r"THUMB_LOWER_(OUTER|INNER|MID)", rest)
    if lower:
        return f"{hand} thumb lower, {lower.group(1).lower()}"
    raise AssertionError(f"unrecognized alias: {alias}")


def group(alias: str) -> str:
    if "_COL" in alias:
        return "main"
    if "_RAISE_" in alias:
        return "raise"
    if "_THUMB_UPPER_" in alias:
        return "upper"
    return "lower"


def format_binding(binding: object) -> str:
    if binding is None:
        return "—"
    if isinstance(binding, dict):
        if binding.get("type") == "trans":
            return "trans"
        parts = [str(binding.get("t", ""))]
        if binding.get("h"):
            parts.append(f"hold {binding['h']}")
        if binding.get("s"):
            parts.append(f"shift {binding['s']}")
        return " / ".join(part for part in parts if part)
    text = str(binding)
    return "none" if text == "" else text


def escape_cell(text: str) -> str:
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("`", "\\`")


def alias_lines(alias: str, limit: int = 13) -> list[str]:
    if len(alias) <= limit:
        return [alias]
    parts = alias.split("_")
    best = min(
        range(1, len(parts)),
        key=lambda i: abs(
            len("_".join(parts[:i])) - len("_".join(parts[i:]))
        ),
    )
    return ["_".join(parts[:best]), "_".join(parts[best:])]


def build_rows() -> list[dict[str, object]]:
    import yaml

    defines = parse_defines(HEADER)
    aliases = parse_positions(defines, ALIAS_RE)
    labels = parse_positions(defines, LABEL_RE)
    assert len(aliases) == 50, f"expected 50 aliases, found {len(aliases)}"
    assert len(labels) == 36, f"expected 36 legacy labels, found {len(labels)}"

    transform = parse_transform()
    layout = parse_layout()
    base_layer = yaml.safe_load(PARSED.read_text())["layers"]["Base"]
    assert len(base_layer) == 50, "expected 50 Base bindings"

    rows = []
    for pos in range(50):
        alias = aliases[pos]
        _, _, x, y = layout[pos]
        rows.append(
            {
                "pos": pos,
                "alias": alias,
                "slot": labels.get(pos, LEGACY_SLOTS.get(pos, "")),
                "rc": transform[pos],
                "physical": physical(alias),
                "base": format_binding(base_layer[pos]),
                "group": group(alias),
                "x": x,
                "y": y,
            }
        )
    return rows


def render_markdown(rows: list[dict[str, object]]) -> str:
    lines = [
        "<!-- Generated by scripts/layout_card.py via `just draw-d50`. Do not edit. -->",
        "",
        "# Hillside D50 physical position card",
        "",
        "One row per matrix position. `Alias` is the shared vocabulary",
        "(`config/key-labels/hillside_d50.h`), `Slot`/`Label` the legacy",
        "machine-facing name, `RC` the matrix cell in the transform, and",
        "`Base` the current default-layer binding.",
        "",
        "| Pos | Alias | Slot | RC | Physical | Base |",
        "| --: | :---- | :--- | :-: | :------- | :--- |",
    ]
    for row in rows:
        row_, col = row["rc"]  # type: ignore[misc]
        lines.append(
            "| {pos} | `{alias}` | {slot} | {row_},{col} | {physical} | {base} |".format(
                pos=row["pos"],
                alias=row["alias"],
                slot=escape_cell(str(row["slot"])),
                row_=row_,
                col=col,
                physical=escape_cell(str(row["physical"])),
                base=escape_cell(str(row["base"])),
            )
        )
    lines.append("")
    return "\n".join(lines)


def render_svg(rows: list[dict[str, object]]) -> str:
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-20 -80 1790 540" '
        'font-family="ui-sans-serif, -apple-system, Segoe UI, sans-serif">',
        "<style>",
        f".pos {{ font-size: 24px; font-weight: 700; fill: #202020; }}",
        f".alias {{ font-family: {SVG_FONT}; font-size: 9px; fill: #555; }}",
        ".title { font-size: 20px; font-weight: 700; fill: #202020; }",
        ".note { font-size: 11px; fill: #666; }",
        "</style>",
        '<text class="title" x="0" y="-50">'
        "Hillside D50 physical position map</text>",
        '<text class="note" x="0" y="-28">'
        "position number on top, shared alias below — generated by "
        "`just draw-d50`</text>",
    ]

    legend = [("main", "main column"), ("raise", "raise"), ("upper", "thumb upper"), ("lower", "thumb lower")]
    legend_x = 1120
    for group_name, label in legend:
        fill, stroke = GROUPS[group_name]
        parts.append(
            f'<rect x="{legend_x}" y="-56" width="12" height="12" rx="3" '
            f'fill="{fill}" stroke="{stroke}"/>'
        )
        parts.append(f'<text class="note" x="{legend_x + 18}" y="-45">{label}</text>')
        legend_x += 150

    for row in rows:
        pos = int(row["pos"])  # type: ignore[arg-type]
        alias = str(row["alias"])
        fill, stroke = GROUPS[str(row["group"])]
        x = int(row["x"])  # type: ignore[arg-type]
        y = int(row["y"])  # type: ignore[arg-type]
        cx = x + 50
        parts.append(
            f'<g><rect x="{x}" y="{y}" width="100" height="100" rx="12" '
            f'fill="{fill}" stroke="{stroke}"/>'
        )
        parts.append(f'<text class="pos" x="{cx}" y="{y + 38}" text-anchor="middle">{pos}</text>')
        lines = alias_lines(alias)
        if len(lines) == 1:
            parts.append(
                f'<text class="alias" x="{cx}" y="{y + 62}" text-anchor="middle">'
                f"{html.escape(lines[0])}</text>"
            )
        else:
            parts.append(
                f'<text class="alias" x="{cx}" y="{y + 56}" text-anchor="middle">'
                f"{html.escape(lines[0])}</text>"
            )
            parts.append(
                f'<text class="alias" x="{cx}" y="{y + 68}" text-anchor="middle">'
                f"{html.escape(lines[1])}</text>"
            )
        parts.append("</g>")

    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def main() -> None:
    rows = build_rows()
    MD_OUT.write_text(render_markdown(rows))
    SVG_OUT.write_text(render_svg(rows))
    print(f"layout card: wrote {MD_OUT.relative_to(ROOT)} and {SVG_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
